name: xServer
main: cbp.double0negative.xServer.XServer
authors: [double0negative, MCForger]
version: 0.0.1
commands:
  xserver:
    description: Stats and controls for xserver
    usage: /XServer command or /x command
    aliases: [x]