name: xServer
main: cbp.double0negative.xServer.XServer
version: 0.1.12

commands:
  xserver:
    description: Stats and controls for xserver
    usage: /XServer command or /x command
    aliases: [x]